### ISSUE TITLE
Erro ao receber saldo

### ISSUE THREAD

**Issue by jpr14** [JorgeBeserra/IqOptionApiDotNet#12]
Saudações, antes de mais obrigado pelo trabalho realizado.

Tenho um erro ao obter o dinheiro, sempre me mostra o mesmo e não atualiza ao realizar uma operação binária para saber se ganho ou perco, como posso fazer para saber o resultado da operação.

Isso é feito após a operação binária e sempre mostra o mesmo saldo, não o novo.

 async void balance_api()
        {
            if (await client.ConnectAsync())
            {
                win_api = 0;
                lose_api = 0;
                double balance_api = 0;

                var demo = profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
                if (await client.ChangeBalanceAsync(profile.ToString(), demo.Id))
                {
                    //get user profile
                    //requestId = Guid.NewGuid().ToString().Replace("-", string.Empty); // New
                    profile = await client.GetProfileAsync(requestId);
                    
                 
                        balance_api = Convert.ToDouble(profile.Balance.ToString());
                        if (balance_api >= balance)
                            win_api = balance_api - balance;
                        else
                            lose_api = balance - balance_api;

                        balance = balance_api;
               
                    label3.Text = balance.ToString("N2");
                   
                }
            }
        }

**Comment by JorgeBeserra** [comment]
Bom dia...

Me desculpa pela demora em responder, mas é que estou tentando terminar um ROBO que vou disponibilizar logo logo...

na api existem alguns observadores, então o melhor é ficar escutando esses observadores...

```csharp
IqClientApiDotNet.WsClient.PositionChangedObservable().Subscribe(x => {
 if(x.Status == "closed")
 {
   if (x.Pnl > 0)
   {
   Resultado = "WIN";
   }
   else if (x.Pnl < 0)
   {
   Resultado = "LOSS";
   }
   else if (x.Pnl == 0)
   {
   Resultado = "EMPATE";
    }
 }
});
```

Verifica a lógica de teste pois escrevi isso agora, mas é mais ou menos isso...

Mas uma vez desculpa pela demora, eu vou verificar as notificações no meu celular acho que não vi uma notificação para nova ISSUE

Obrigado por usar a API, assim posso melhorar a documentação...

**Comment by jpr14** [comment]
Saudações, obrigado por nos responder,

Eu tentei isso atribuindo-o a uma variável de string, mas ainda sem resultado. Quando deve ser usado?

string resultado="";
client.WsClient.PositionChangedObservable().Subscribe(x => {
                if (x.Status == "closed")
                {
                    if (x.Pnl > 0)
                    {
                        resultado = "WIN";
                    }
                    else if (x.Pnl < 0)
                    {
                        resultado = "LOSS";
                    }
                    else if (x.Pnl == 0)
                    {
                        resultado = "EMPATE";
                    }
                }
            });

**Comment by JorgeBeserra** [comment]
Mandei esse código como exemplo de uma OBSERVABLE... mas tem um para o BALANCE... 

ele fica ouvindo quando há alteração de saldo...

```csharp
IqClientApiDotNet.BalanceChangedObservable.Subscribe(x =>
{
 Console.WriteLine(x.CurrentBalance.NewAmount);
});
```

Ainda não tive tempo de criar o WIKI, mas vou relacionar todos os Observables...

**Comment by jpr14** [comment]
Obrigado, com esse método funcionou
