### ISSUE TITLE
Resultado da Ordem de Compra

### ISSUE THREAD

**Issue by JimAlmeida** [JorgeBeserra/IqOptionApiDotNet#13]
Olá Jorge,

Sua API é bem interessante, pretendo usá-la para projetos futuros. Porém estava estudando e testando a API, e não consegui ver algum método que me retornasse o resultado de uma compra se eu passasse o ID da posição (BinaryOptionsResult.PositionId). Teria algum método disponível na API para retornar esse resultado? É bem importante, principalmente na aplicação de estratégias com Martingale. Se for uma feature ainda não disponível, poderia me dizer como está a previsão/progresso de desenvolvimento?

**Comment by JorgeBeserra** [comment]
Bom dia... 

Desculpa a demora... verifica os OBSERVADORES....

```csharp
IqClientApiDotNet.WsClient.PositionChangedObservable().Subscribe(x => {
 if(x.Status == "closed")
 {
   if (x.Pnl > 0)
   {
   Resultado = "WIN";
   }
   else if (x.Pnl < 0)
   {
   Resultado = "LOSS";
   }
   else if (x.Pnl == 0)
   {
   Resultado = "EMPATE";
   }
 }
});
```

Na variável X terá o ID, porém como a IQ retorna diversas compras na hora de observar... tem que testar a ARRAY de ids... 

Eu dei uma parada nas atualizações da API pois estou preparando o DigestingDuck é um robo que vou liberar ainda essa semana, e como é um projeto em andamento ainda esta cheio de BUGS... ai conto com a ajuda de todos vocês para melhorar...

Obrigado por usar a API

**Comment by jpr14** [comment]
Onde posso encontrar o robô que você está fazendo?

**Comment by jpr14** [comment]
E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?

**Comment by JorgeBeserra** [comment]
> 
> 
> E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?

Boa Tarde,

De qual chamada o preço esta retornando inteiro?!?

Aguardo...

**Comment by JorgeBeserra** [comment]
> 
> 
> Onde posso encontrar o robô que você está fazendo?

Ainda estou arrumando uns problema de x86 e x64, testei em umas VM com 32 bits e 64 e da erro... por conta de uma biblioteca que estou usando...

mas vou liberar assim que estiver com isso resolvido...

**Comment by jpr14** [comment]
> > E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?
> 
> Boa Tarde,
> 
> De qual chamada o preço esta retornando inteiro?!?
> 
> Aguardo...

Aqui, o parâmetro int size não permite operações de  $1.5 , por exemplo

BuyAsync(requestId, ActivePair.EURUSD, 1, OrderDirection.Call, exp);

**Comment by JorgeBeserra** [comment]
> 
> 
> > > E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?
> > 
> > 
> > Boa Tarde,
> > De qual chamada o preço esta retornando inteiro?!?
> > Aguardo...
> 
> Aqui, o parâmetro int size não permite operações de $1.5 , por exemplo
> 
> BuyAsync(requestId, ActivePair.EURUSD, 1, OrderDirection.Call, exp);

Atualizado 1.0.9

Pensei em colocar Double mas já tive problemas com ele... então alterei direto para Decimal mesmo... afinal de contas se encaixa melhor... 

Faz um teste e me avisar, por favor..

**Comment by jpr14** [comment]
Eu experimentei e já está perfeito, obrigado pela pronta resposta

**Comment by jpr14** [comment]
> > > > E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?
> > > 
> > > 
> > > Boa Tarde,
> > > De qual chamada o preço esta retornando inteiro?!?
> > > Aguardo...
> > 
> > 
> > Aqui, o parâmetro int size não permite operações de $1.5 , por exemplo
> > BuyAsync(requestId, ActivePair.EURUSD, 1, OrderDirection.Call, exp);
> 
> Atualizado 1.0.9
> 
> Pensei em colocar Double mas já tive problemas com ele... então alterei direto para Decimal mesmo... afinal de contas se encaixa melhor...
> 
> Faz um teste e me avisar, por favor..

Eu experimentei e já está perfeito, obrigado pela pronta resposta

**Comment by JorgeBeserra** [comment]
> 
> 
> > > > > E você poderia colocar o preço como decimal e não inteiro? serviria para algumas estratégias de juros compostos?
> > > > 
> > > > 
> > > > Boa Tarde,
> > > > De qual chamada o preço esta retornando inteiro?!?
> > > > Aguardo...
> > > 
> > > 
> > > Aqui, o parâmetro int size não permite operações de $1.5 , por exemplo
> > > BuyAsync(requestId, ActivePair.EURUSD, 1, OrderDirection.Call, exp);
> > 
> > 
> > Atualizado 1.0.9
> > Pensei em colocar Double mas já tive problemas com ele... então alterei direto para Decimal mesmo... afinal de contas se encaixa melhor...
> > Faz um teste e me avisar, por favor..
> 
> Eu experimentei e já está perfeito, obrigado pela pronta resposta

TMJ..!!!
