### ISSUE TITLE
BuyAsync | Cannot purchase an option (active is suspended)

### ISSUE THREAD

**Issue by GerritKnoetze** [JorgeBeserra/IqOptionApiDotNet#177]
Good day @JorgeBeserra,
If I run sample 15) OpenBinaryOptionsSample, I get a response result back "Cannot purchase an option (active is suspended)"
Authentication is fine, get real-time data is fine, this result is on all pairs if I try to open any order. [IqClientApiDotNet.BuyAsync]

**Any suggestions what the cause could be?**

public override async Task RunSample()
{
   if (await IqClientApiDotNet.ConnectAsync())
   {
      string requested;
      while (true)
      {
         await Task.Delay(5000);
         requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
         var result = await IqClientApiDotNet.BuyAsync(requestId, BalanceType.Practice, ActivePair.EURUSD_OTC, (decimal)1.5, OrderDirection.Call, DateTimeOffset.Now);   //<<<RESULT HERE
         Console.WriteLine($"PositionId = {result.PositionId}");
      }
   }
}

**Comment by JorgeBeserra** [comment]
> Good day @JorgeBeserra, If I run sample 15) OpenBinaryOptionsSample, I get a response result back "Cannot purchase an option (active is suspended)" Authentication is fine, get real-time data is fine, this result is on all pairs if I try to open any order. [IqClientApiDotNet.BuyAsync]
> 
> **Any suggestions what the cause could be?**
> 
> public override async Task RunSample() { if (await IqClientApiDotNet.ConnectAsync()) { string requested; while (true) { await Task.Delay(5000); requestId = Guid.NewGuid().ToString().Replace("-", string.Empty); var result = await IqClientApiDotNet.BuyAsync(requestId, BalanceType.Practice, ActivePair.EURUSD_OTC, (decimal)1.5, OrderDirection.Call, DateTimeOffset.Now); //<<<RESULT HERE Console.WriteLine($"PositionId = {result.PositionId}"); } } }

Hello how are you, I hope everything is in order, next... 

IqOption made some changes and deactivated some of the pairs, so a colleague from the community passed the changes to me and I added them, please try some of these below and let me know... Waiting...

GBPJPY_op
AUDJPY_op
NZDUSD_op
EURGBP_op
AUDUSD_op
EURUSD_op
AUDCAD_op
USDJPY_op
GBPUSD_op
EURJPY_op

Good luck

**Comment by GerritKnoetze** [comment]
The new pairs seem to be working with _op. Thank you for your feedback and quick response! :-)

GBPJPY_op
AUDJPY_op
NZDUSD_op
EURGBP_op
AUDUSD_op
EURUSD_op
AUDCAD_op
USDJPY_op
GBPUSD_op
EURJPY_op
