### ISSUE TITLE
Contribuição para desenvolvimento

### ISSUE THREAD

**Issue by fabiomdj** [JorgeBeserra/IqOptionApiDotNet#2]
Olá Jorge,

Gostaria de saber se vc aceita ajuda pra desenvolver esta api, trabalho com C# e estou entrando pro mundo do traders tb.
Senti falta de um método para pegar o resultado de um 'Position'.

**Comment by JorgeBeserra** [comment]
Fabio,

Opa... toda ajuda é bem vinda... já existe algumas REQUEST para GET_POSITION porém a IQ esta retornando erro... se conseguir descobrir o problema será ótimo... durante o dia estou trabalhando mas depois das 18:00 to ficando exclusivo para a API... já fiz mais algumas coisas... porém não subi ainda...

Seja bem vindo... !!!!

**Comment by fabiomdj** [comment]
Tudo bem, não estou muito familiarizado com Core e a estrutura dele, se puder me mostrar o caminho pra iniciar os request.
Segue meu e-mail: fabiomdj@gmail.com, pra melhorar a comunicação.

**Comment by slobodafabiano** [comment]
Boa noite Fabiomdj, teria como me auxiliar pra instalar 
Trabalho com o .net Framework, nunca mexi com esse core
Porem quero implementar a parte gráfica a partir dessa api, Wpp> 41 995450783
Obrigado.

**Comment by fabiomdj** [comment]
Boa noite

> Boa noite Fabiomdj, teria como me auxiliar pra instalar
> Trabalho com o .net Framework, nunca mexi com esse core
> Porem quero implementar a parte gráfica a partir dessa api, Wpp> 41 995450783
> Obrigado.

Boa noite,
Eu também estou na mesma situação, nunca trabalhei antes com o core, só com .net antigo.
Mas, estou olhando aqui, parece que estou fazendo sucesso.

**Comment by fabiomdj** [comment]
> Fabio,
> 
> Opa... toda ajuda é bem vinda... já existe algumas REQUEST para GET_POSITION porém a IQ esta retornando erro... se conseguir descobrir o problema será ótimo... durante o dia estou trabalhando mas depois das 18:00 to ficando exclusivo para a API... já fiz mais algumas coisas... porém não subi ainda...
> 
> Seja bem vindo... !!!!

Consegui executar o método pra pegar um PositionID porém, este método parece não retornar nada, acho que deve ser algo que estou deixando de fazer, mas, consegui logar na conta, pegar secure code e chamar o método pra pegar o id, porém, não vejo o resultado.
Pelo menos erro não está dando.

**Comment by fabiomdj** [comment]
Criei um grupo no zap pra gente interagir: https://chat.whatsapp.com/H4bIanz5Ho84zoDmR81lZ1

**Comment by JorgeBeserra** [comment]
Resolvido, o mesmo estava deixando de se inscrever nos canais.
