### ISSUE TITLE
Hoje é um erro tentar mudar o saldo para o prático ou real

### ISSUE THREAD

**Issue by jpr14** [JorgeBeserra/IqOptionApiDotNet#20]
Saudações, obrigado pelo privilégio de permitir o uso desta api.

Hoje é um erro tentar mudar o saldo para o prático ou real

var demo = profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
                await client.ChangeBalanceAsync(profile.ToString(), demo.Id);

Esse erro começou a me dar algumas horas atrás

**Comment by gabrielbsin** [comment]
Bom dia,

Também tenho tido esse problema.

System.NullReferenceException: Referência de objeto não definida para uma instância de um objeto.

**Comment by brunoshady** [comment]
Mesmo problema aqui...

Pelo que percebi, o profile.Balances não tem nada, me parece uma lista vazia e por isso ocorre o erro.

Alguma solução?

**Comment by brunoshady** [comment]
Na real, analisei melhor aqui e parece que ta rolando um BadRequest quando tenta dar um ChangeBalanceRequest, e como não vem um retorno valido, o método ChangeBalanceAsync acaba retornando nulo ocasionando o erro.

Estranho pois existe uma lib aqui em python que ainda consegue mudar o balance pra demo, mas não consegui identificar como ela faz isso.

**Comment by elyelrubens** [comment]
O que está acontecendo é que não está carregando as carteiras. profile.Balances vindo sem registros. prém no retorno da iqoption o resultado bem com um array Balances com as informações.

**Comment by brunoshady** [comment]
Ok, mas não é esse o problema de fato.
Eu consegui pegar o Id do Balance da minha conta demo (por outra lib em python) e passei diretamente o Id pro ChangeBalanceAsync e mesmo assim ocorre erro.

**Comment by elyelrubens** [comment]
Parece um erro de conversão do json para o objeto Balance. Mas não consegui resolver nada ainda. Alguém com alguma solução?

**Comment by gabrielbsin** [comment]
Boa tarde Galera,

Eu parei de receber o BadRequest depois que removi o ParameterType.QueryString e mudei para ParameterType.GetOrPost, mas ainda não tinha resolvido o problema.

Então como o método Buy de binária e digital pega uma variável BalanceId é possível usar o código baixo:

var tipoContaSettings = Properties.Settings.Default.conta_t_r;
long balanceId = 0;
foreach (Balance balance in client.WsClient.Profile.Balances) {
             if (balance.Type == (tipoContaSettings == "Treinamento" ? BalanceType.Practice : BalanceType.Real)) balanceId = balance.Id;
}
client.WsClient.Profile.BalanceId = balanceId;

**Comment by brunoshady** [comment]
Outro exemplo, talvez mais fácil

_client.WsClient.Profile.BalanceId = _client.WsClient.Profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice).Id;
