### ISSUE TITLE
RequestLeaderboardUserinfoDealsClientAsync

### ISSUE THREAD

**Issue by gabrielbsin** [JorgeBeserra/IqOptionApiDotNet#3]
Primeiramente, muito obrigado por atualização está API! :)

Estou com um problema ao utilizar o metodo RequestLeaderboardUserinfoDealsClientAsync, quando eu envio a requisição e vou ver  o resultado ele me retorna assim:

{"user_id":0,"country_id":0,"top_type":0,"top_size":0,"position":0,"score":0}

Porém, no trace do console ele sai assim:

IqOptionApiDotNet: Trace: ⬇ {"request_id":"b09a8406deb247adb53b502dda4a600b","name":"leaderboard-userinfo-deals-client","msg":{"isSuccessful":true,"result":{"country_id":30,"entries_by_country":{"0":{"count":50,"flag":"","position":15239,"score":169.81,"top_size":233890,"user_id":77357676},"30":{"count":50,"flag":"BR","position":8337,"score":169.81,"top_size":146029,"user_id":77357676}},"requested_user_id":77357676,"user_id":58887593}},"status":2000}

Fiz exatamente como está no READ:

requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
var leader = await api.RequestLeaderboardUserinfoDealsClientAsync(requestId, countryes, userId);
ReceberMensagem(JsonConvert.SerializeObject(leader));

Obrigado!!

**Comment by JorgeBeserra** [comment]
@gabrielbsin Obrigado..!!

RequestLeaderboardDealsClientAsync -> Pega os traders do RANKING da IQ.. vai te listar os dados desses usuarios...
RequestLeaderboardUserinfoDealsClientAsync -> Serve mais para atualizar e ver se um determinado usuario esta On-Line qual o seu nivel no ranking quanto ele ganho na semana e outras coisas mais.

Então o mais interessante séria... primeiro tem que fazer é pegar todos os IDS dos traders que deseja seguir, pois eu estou achando que na segunda função deve ter colocado o seu id e quando retornar ele vai voltar o seu status.

0 -> é o mundo todo...
191 -> O seu Pais de origem.
1 é do Trader Numero 1 
10 é até o Trader numero 10
ai no resto da função não tem necessidade de mexer...

```csharp
requestId = Guid.NewGuid().ToString().Replace("-", string.Empty); // New
var leaderboard = await client.RequestLeaderboardDealsClientAsync(requestId, 0, 191, 1, 10, 64, 64, 64, 64, 2);
```

![image](https://user-images.githubusercontent.com/5083403/90703067-2a726080-e263-11ea-8ef9-ecc43dacb72a.png)

Ele tem que voltar esses dados aqui... 

  Depois de posse dos IDS essa rotina abaixo serve para consultar os detalhes de um ID de outro usuário é como se fosse quando você passa o mouse em cima do usuario dessa forma.. 

![image](https://user-images.githubusercontent.com/5083403/90703165-6c9ba200-e263-11ea-84f3-30450e89aa6c.png)

```csharp
  requestId = Guid.NewGuid().ToString().Replace("-", string.Empty); // New
  long[] countryes = {0 };
  var userId = ""; // <-- Id do Usuario aqui!
  var leader = await client.RequestLeaderboardUserinfoDealsClientAsync(requestId, countryes, userId);
```

Lembre-se para capturar as entradas dos outros usuarios tem que se inscrever no seguinte TÓPICO, basta executar essa função:

```csharp
IqClientApiDotNet.WsClient.LiveDealObservable().Subscribe(x => {
_logger.Information( $"Posição: {x.PositionId} Entrada: {x.UserId} Created {x.CreatedAt} Amount: {x.AmountEnrolled} Direction: {x.InstrumentDir} Diferença de Tempo: {difference} Ativo: {x.ActiveId} Expiracao {x.ExpirationType}");
});
```

Posso estar equivocado, mas creio que seja mais ou menos isso que você esteja precisando...

**Comment by gabrielbsin** [comment]
@JorgeBeserra obrigado pela explicação!

Gostaria de aproveitar o tópico, eu também recentemente tenho obtido um erro com a função RequestLeaderboardDealsClientAsync, ele acontece quando um lista é muito grande. Por exemplo, quando eu coloco pra receber uma lista dos tops trades de 1 a 50 ele me retorna isso:

System.Threading.Tasks.TaskCanceledException: Uma tarefa foi cancelada.
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

Exceção gerada: 'System.Threading.Tasks.TaskCanceledException' em mscorlib.dll

O estranho é que, o erro da a cada 2x ou 3x vezes ai ele funciona 2x e volta a retorna essa mensagem.

Tentei colocar como ConfigureAwait(false);

Mas nada resolveu, não sei sé o tamanho da lista que ta retornando com demora e ultrapassando o limite max de 5 secs.

Agradeço sua atenção!

**Comment by damianportillo** [comment]
@JorgeBeserra 
all the time I have the exception: A task was canceled.

var api = new IqOptionApiDotNetClient("email@gmail.com", "pass");
if (await api.ConnectAsync())
{
var requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
CountryType[] countryes = { CountryType.AR, };
var userId = 8888888888888;
var leader = await api.RequestLeaderboardUserinfoDealsClientAsync(requestId, countryes, userId);
Console.WriteLine(JsonConvert.SerializeObject(leader));
}
