### ISSUE TITLE
Erro ao conectar api IqOptionApiDotNetClient 23/10/2020

### ISSUE THREAD

**Issue by jpr14** [JorgeBeserra/IqOptionApiDotNet#31]
Erro ao conectar api IqOptionApiDotNetClient, desde ontem não faz login na minha conta iqoption

client = new IqOptionApiDotNetClient(email.Text, password.Text);

 if (await client.ConnectAsync())
 {

} 
else {

}

vá diretamente para else , alguma solução?

**Comment by jpr14** [comment]
@JorgeBeserra please try updating https://auth.iqoption.com/api/v1.0/login to https://auth.iqoption.com/api/v2/login

**Comment by JorgeBeserra** [comment]
Opa, @jpr14 

Muito obrigado pelo alerta, andou envolvido em outros projetos e acabei não utilizando mais a API, 

Mas ficarei muito grato se conseguir testar agora, pois nos meus testes esta logando e como a V2 tem algumas alterações demorei um pouco mais...

Já publiquei no NUGET

**Comment by jpr14** [comment]
Obrigado, pude entrar novamente
