### ISSUE TITLE
Conexão aparentemente não esta funcionando.

### ISSUE THREAD

**Issue by Anderson-SG** [JorgeBeserra/IqOptionApiDotNet#48]
`if (await _iqClient.ConnectAsync())`

Retornando False sempre, mesmo com usuario e senha corretos.

**Comment by JorgeBeserra** [comment]
> 
> 
> `if (await _iqClient.ConnectAsync())`
> 
> Retornando False sempre, mesmo com usuario e senha corretos.

Você esta testando pelos SAMPLES ?!?,

Favor colocar o log da saída...

**Comment by Anderson-SG** [comment]
@JorgeBeserra, Na verdade nada é exibido no console, Sim testei pelos samples e por meu codigo.
Aparamente o Payload e URL de Login mudaram. 

Este problema esta sendo relatado no projeto original também !
https://github.com/MongkonEiadon/IqOption.Net/issues/67

**Comment by Anderson-SG** [comment]
@JorgeBeserra Pequeno update..

Pequena mudança no codigo da task para conseguir acompanhar o Status da mesma... Fica "WaitingForActivation "para  sempre.

![image](https://user-images.githubusercontent.com/37317374/100395959-e345f980-3021-11eb-9814-2f1681e9e2f4.png)

**Comment by Anderson-SG** [comment]
Resolvido, o problema é relativo a conta do usuário não a código.
