### ISSUE TITLE
ChangeBalanceAsync() Quebrou.

### ISSUE THREAD

**Issue by Anderson-SG** [JorgeBeserra/IqOptionApiDotNet#49]
**ChangeBalanceAsync() Quebrou, todas as requests para esse endpoint Retornam "BadRequest";**

**Passos para reproduzir:** 

`var demo = client.WsClient.Profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);`
`requestId = Guid.NewGuid().ToString().Replace("-", string.Empty); // New`
`await client.ChangeBalanceAsync(requestId, demo.Id);`

![image](https://user-images.githubusercontent.com/37317374/100400744-480b4f00-3036-11eb-83bf-1dc15236e1c1.png)

**Update:** 
Aparentemente a troca entre tipo de saldo (DEMO/REAL) virou um pacote a ser enviado via websocket e não mais POST, Segue evidencia.

`{"name":"sendMessage","request_id":"173","local_time":36277,"msg":{"name":"set-user-settings","version":"1.0","body":{"name":"traderoom_gl_common","version":3,"client_id":"XXXXXXXXXXXXXCENSURADOXXXXXXXXXXXXX","config":{"balanceId":278241358,"theme":"blue","isSoundDisabled":false,"openedLeftPanelSections":"","isPlotCandleWidthAutoChanged":true,"assetSortConfig":{"binary|":"cur_price_profit_big_to_small","cfd|":"volume_desc","cfd|Commodity":"volume_desc","cfd|ETF":"volume_desc","cfd|Stock":"volume_desc","crypto|":"volume_desc","digital-option|":"volume_desc","exchange|":"marketcap_desc","forex|":"volume_desc","fx-option|":"nextexp_asc","multi-option|":"simple"},"lastSelectedActiveCategory":"binary","portfolioLastSorting":"default","customSettings":{},"isPosDashedLineVisible":true,"notAutoSelectClosestStrike":true,"isNewOptionInCurrentTab":false,"isShowClosedDealPopup":true,"isShowPendingOption":false,"isHideBalance":false,"isShowBidAskOnPlot":true,"isShowBgMap":true,"isShowDottedOptionLine":true,"isHideChangePositionNotification":false,"isHideFeedTopTraders":false,"isShowOptionAmountOnPlot":true,"topOnWorld":true,"notHideAllStrike":true,"tradingLeverages":{},"favoriteEmoji":[],"portfolioWithoutInvestment":false,"alreadySettedFlags":["auto_margin","auto_margin_included","hide_multipliers_disabled_pro"],"lastCandles":{"binary":5,"turbo":5,"digital-option":5,"cfd":3600,"forex":10,"crypto":1800,"fx-option":5},"isPriceMovementsNotification":true,"isShowAlertsNotification":true,"leftPanelButtonsStates":["Portfolio&&true","History&&true","Chat&&true","Leaderboard&&true","MarketAnalysis&&true","Tournaments&&false","FAQ&&false","Tutorials&&true","Alerts&&false","ShowMore&&true"],"selectedMarketAnalysisTab":"MARKET_NEWS","marginBalanceWasUsed":false,"marginBannerWasClosed":false,"marginPlotTypeWasChanged":false,"isIqGuardDisabled":false}}}}`

![image](https://user-images.githubusercontent.com/37317374/100401423-2e6b0700-3038-11eb-84a1-14675a7f4d15.png)

**Comment by JuniorCosta** [comment]
Conseguiu resolver Anderson?

**Comment by JuniorCosta** [comment]
Dá uma olhada nesse issue aqui.. resolvi por ele amigo..
https://github.com/JorgeBeserra/IqOptionApiDotNet/issues/20

**Comment by Anderson-SG** [comment]
@JuniorCosta Funcionou, muito obrigado !
