### ISSUE TITLE
How Fix Conection Error I Found the Solution

### ISSUE THREAD

**Issue by jpr14** [JorgeBeserra/IqOptionApiDotNet#54]
Hi @JorgeBeserra today the api has this error |Fatal|WebSocket.connect:0|An error has occurred during a TLS handshake.

To fix this only add:
WebSocketClient.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;

in InitialSocket()

protected virtual void InitialSocket(string secureToken)
        {
            string requestId;
            WebSocketClient = new WebSocket("wss://iqoption.com/echo/websocket");

            **WebSocketClient.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;**

            WebSocketClient.OnError += (sender, args) =>
            {
                _logger.LogError($"WebSocket Error : {args.Message}");
            };
            
            WebSocketClient.Connect();

            var scheduler = new EventLoopScheduler();
            MessageReceivedObservable =
                Observable.Using(
                        () => WebSocketClient,
                        _ => Observable
                            .FromEventPattern<EventHandler<MessageEventArgs>, MessageEventArgs>(
                                handler => _.OnMessage += handler,
                                handler => _.OnMessage -= handler))
                    .Select(x => x.EventArgs.Data)
                    .SubscribeOn(scheduler)
                    .Publish()
                    .RefCount();

            WebSocketClient.OnMessage += (sender, args) => SubscribeIncomingMessage(args.Data);

            SystemReconnectionTimer.AutoReset = true;
            SystemReconnectionTimer.Enabled = true;
            SystemReconnectionTimer.Elapsed += (sender, args) =>
            {
                _logger.LogWarning("System try to reconnect");
                requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
                SendMessageAsync(requestId, new SsidWsMessageBase(secureToken)).ConfigureAwait(false);
            };

            // send secure token to connect to server
            requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
            SendMessageAsync(requestId, new SsidWsMessageBase(secureToken), ProfileObservable).Wait();

            // send order changed subscribe
            InitialSubscribeOrderChanged();
        }

**Comment by JorgeBeserra** [comment]
Thanks...!!!

@jeffersonmello

During the tests, I only needed to invert the lines because WS was not created yet ... It's people like you that make the OpenSource world better ... !!!

WebSocketClient = new WebSocket("wss://iqoption.com/echo/websocket");
WebSocketClient.SslConfiguration.EnabledSslProtocols = System.Security.Authentication.SslProtocols.Tls12;

I'll just adjust the DLL to release the package and update the version...
