### ISSUE TITLE
Alterar modo de conta para DEMO e REAL

### ISSUE THREAD

**Issue by luciolhl** [JorgeBeserra/IqOptionApiDotNet#61]
Não estou conseguido achar o método para alterar de conta demo para real mas vi que possui um ENUM para indicar se é com DEMO ou REAL mas não consigo achar métodos que faz a alteração de contas. Vi em um outro repositório em Python que tem uma função chamada change_balance que é para alterar de REAL para DEMO informando os valores PRACTICE ou REAL. Nesse repositório aqui como é feito essa alteração?

**Comment by jeffersonmello** [comment]
Olá, no meu caso estou fazendo da seguinte forma:


`Client.WsClient.Profile.BalanceId = Client.WsClient.Profile.Balances.First(x => x.Type == balanceType).Id;`

onde `balanceType`  é o enum `BalanceType`

**Comment by luciolhl** [comment]
Consegui resolver o problema dessa forma:

       public static bool AlteraTipoDeConta(Config config)
        {
            if (client.IsConnected)
            {
                foreach (Balance balance in client.WsClient.Profile.Balances)
                {
                    if (config.tipo_conta == Constantes.Conta.TIPO_CONTA_TREINAMENTO)
                    {
                        if (balance.Type == BalanceType.Practice)
                        {
                            profile.Balance = balance.Amount;
                            profile.BalanceId = balance.Id;
                            profile.BalanceType = BalanceType.Practice;
                            client.WsClient.Profile.Balance = balance.Amount;
                            client.WsClient.Profile.BalanceId = balance.Id;
                            client.WsClient.Profile.BalanceType = BalanceType.Practice;
                            idBalanceDemo = balance.Id;
                            balanceId = balance.Id;
                        }
                    }
                    if (config.tipo_conta == Constantes.Conta.TIPO_CONTA_REAL)
                    {
                        if (balance.Type == BalanceType.Real)
                        {
                            profile.Balance = balance.Amount;
                            profile.BalanceId = balance.Id;
                            profile.BalanceType = BalanceType.Real;
                            client.WsClient.Profile.Balance = balance.Amount;
                            client.WsClient.Profile.BalanceId = balance.Id;
                            client.WsClient.Profile.BalanceType = BalanceType.Real;
                            idBalanceReal = balance.Id;
                            balanceId = balance.Id;
                        }
                    }
                }
                return true;
            }
            return false;
        }

**Comment by luciolhl** [comment]
Resolvido
