### ISSUE TITLE
Balance Practice

### ISSUE THREAD

**Issue by xxxmpsxxx** [JorgeBeserra/IqOptionApiDotNet#66]
Existe alguma forma de utilizar essa API para "fazer testes" com a conta de pratica? Não consegui utilizar o Balance com o valor de practice que aparece logando direto na iqoption...

Obrigado.

**Comment by jeffersonmello** [comment]
De uma olhada nesta issue que foi resolvida: https://github.com/JorgeBeserra/IqOptionApiDotNet/issues/61

**Comment by xxxmpsxxx** [comment]
ok, consegui resolver como vc fez, client.WsClient.Profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
Vlw.

**Comment by tiagoccosta** [comment]
Tentei de ambas as formas de trocar para o pratice... nada funciona.

client.WsClient.Profile.BalanceId = client.WsClient.Profile.Balances.First(x => x.Type == balanceType).Id;

se executo client.GetProfileAsync(requestId) recebo que estou com o balance real;


O código do Sample causa um NullreferenceException
var demo = profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
await client.ChangeBalanceAsync(requestId, demo.Id);

**Comment by xxxmpsxxx** [comment]
Resolvido
