### ISSUE TITLE
ChangeBalanceSample.cs -> Balances = {IqOptionApiDotNet.Models.Balance[0]}

### ISSUE THREAD

**Issue by damianmatiasmmax** [JorgeBeserra/IqOptionApiDotNet#77]
Buen dia a todos
Estoy teniendo el siguiente problema, en: 

ChangeBalanceSample.cs
            string requestId;
            if (await IqClientApiDotNet.ConnectAsync())
            {
                requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
                var profile = await IqClientApiDotNet.GetProfileAsync(requestId);

En esta line, el "profile.Balance" es igual a 0, por lo que las siguientes líneas de programación tiran error. 

![ChangeBalanceSample](https://user-images.githubusercontent.com/70164557/116486828-e5c4ad80-a864-11eb-904b-7480de2fdbcd.png)

Ustedes podrian ayudarme para solucionar este problema?

Desde ya muchas gracias
Abrazo
Damian

**Comment by damianmatiasmmax** [comment]
Lo pude resolver con la ayuda de este ejemplo:
https://github.com/MongkonEiadon/IqOption.Net/issues/65

Y este es el codigo de prueba que me funciono:
               string requestId2 = Guid.NewGuid().ToString().Replace("-", string.Empty);
                await this.IqClientApiDotNet.GetProfileAsync(requestId2);
                long balanceId = 0;
                foreach (Balance balance in this.IqClientApiDotNet.WsClient.Profile.Balances)
                {
                    if (balance.Type == BalanceType.Practice) balanceId = balance.Id;
                }
                this.IqClientApiDotNet.WsClient.Profile.BalanceId = balanceId;


                requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
                var demo = IqClientApiDotNet.WsClient.Profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
             
                if (await IqClientApiDotNet.ConnectAsync())
                {
                    string requestId3;
                    while (true)
                    {
                        IqClientApiDotNet.WsClient.Profile.BalanceId = demo.Id;
                        await Task.Delay(5000);
                        requestId3 = Guid.NewGuid().ToString().Replace("-", string.Empty);
                        decimal Inversion = 1.5m;
                        var result = await IqClientApiDotNet.BuyAsync(requestId, ActivePair.EURUSD, Inversion, OrderDirection.Call, DateTimeOffset.Now);
                        Console.WriteLine($"PositionId = {result.PositionId}");
                        Console.WriteLine($"Error = {result.ErrorMessage}");

                    }
                }


Muchas gracias
Abrazo

**Comment by damianportillo** [comment]
GRACIAS ME SIRVIÓ TAMBIEN, COMPARTO MI CODIGO
using IqOptionApiDotNet;
using IqOptionApiDotNet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebSocketSharp;

namespace IQapi
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var api = new IqOptionApiDotNetClient("correo@gmail.com", "contraseña");
                       var requestId = string.Empty; // New

            try
            {
                //logging in
                if (await api.ConnectAsync())
                {
                    requestId = Guid.NewGuid().ToString().Replace("-", string.Empty);
                    var demo = api.WsClient.Profile.Balances.FirstOrDefault(x => x.Type == BalanceType.Practice);
                    api.WsClient.Profile.BalanceId = demo.Id;
                    await Task.Delay(5000);
                    var requestId3 = Guid.NewGuid().ToString().Replace("-", string.Empty);
                    decimal Inversion = 100;
                    var exp = DateTime.Now.AddMinutes(2);
                    var result = await api.BuyAsync(requestId, ActivePair.EURJPY_OTC, Inversion, OrderDirection.Call, exp);
                    Console.WriteLine($"PositionId = {result.PositionId}");
                    Console.WriteLine($"Error = {result.ErrorMessage}");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            finally
            {
                Console.ReadLine();
            }
        }
    }
}
